// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace McqExaminationSystem.Models;

[Table("Exam")]
public partial class Exam
{
    [Key]
    public int ExamId { get; set; }

    [Required]
    [StringLength(50)]
    public string ExamName { get; set; }

    [StringLength(300)]
    public string ExamDescription { get; set; }

    [DefaultValue(false)]
    public bool IsDeleted { get; set; }

    [InverseProperty("Exam")]
    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();

    [InverseProperty("Exam")]
    public virtual ICollection<UserExamRelation> UserExamRelations { get; set; } = new List<UserExamRelation>();
}