// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;

namespace McqExaminationSystem.Models;

public partial class McqExaminationSystemDbContext : DbContext
{
    public McqExaminationSystemDbContext(DbContextOptions options) : base(options) { }

    public virtual DbSet<Exam> Exams { get; set; }

    public virtual DbSet<Question> Questions { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserExamRelation> UserExamRelations { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Exam>(entity =>
        {
            entity.HasIndex(p => p.ExamName).IsUnique();
        });

        modelBuilder.Entity<Question>(entity =>
        {
            entity.HasOne(d => d.Exam).WithMany(p => p.Questions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Question_Exam");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasIndex(u => u.UserName).IsUnique();
        });

        modelBuilder.Entity<UserExamRelation>(entity =>
        {
            entity.HasOne(d => d.Exam).WithMany(p => p.UserExamRelations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserExamRelation_Exam");

            entity.HasOne(d => d.User).WithMany(p => p.UserExamRelations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserExamRelation_User");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}