// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace McqExaminationSystem.Models;

[PrimaryKey("UserId", "ExamId")]
[Table("UserExamRelation")]
public partial class UserExamRelation
{
    [Key]
    public long UserId { get; set; }

    [Key]
    public int ExamId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ExamDateAndTime { get; set; }

    public int ExamScore { get; set; }

    [DefaultValue(false)]
    public bool IsDeleted { get; set; }

    [ForeignKey("ExamId")]
    [InverseProperty("UserExamRelations")]
    public virtual Exam Exam { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("UserExamRelations")]
    public virtual User User { get; set; }
}