// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace McqExaminationSystem.Models;

[Table("User")]
public partial class User
{
    [Key]
    public long UserId { get; set; }

    [Required]
    [StringLength(50)]
    public string UserName { get; set; }

    [Required]
    [StringLength(300)]
    public string FullName { get; set; }

    [Required]
    [StringLength(100)]
    public string Email { get; set; }

    [Required]
    [StringLength(50)]
    public string Password { get; set; }

    [Required]
    [NotMapped]
    public string ConfirmPassword { get; set; }

    [Required]
    [StringLength(50)]
    public string Role { get; set; }

    [DefaultValue(false)]
    public bool IsDeleted { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<UserExamRelation> UserExamRelations { get; set; } = new List<UserExamRelation>();
}